### ISSUE TITLE
Check in when you done with exercises

### ISSUE THREAD

**Issue by xiao8579** [xiao8579/QuickCapture-Testing#12]
**Please check in your names here when you done with the exercises.** 💯 

- [ ] Ahjung Kim
- [ ] Ayed Al-Thobaiti
- [ ] Bassem Halawi
- [ ] Chase Fisher
- [ ] Danielle Hopkins
- [ ] Elliot Plack
- [ ] Fadil Abuzour
- [ ] Faisal Basudan
- [ ] Jason Kline
- [ ] Ken Oetzel
- [x] Leandro Zamudio
- [x] Megan Engel
- [ ] Michael Penokie
- [ ] Rafael Casagrande
- [ ] Ryan Branch
- [ ] Severine Boll
- [ ] Steven Wheatley
- [ ] Susana Carvajal
- [ ] Tanner Wride
- [x] Elliot Plack
- [ ] Jason Ritter

**Comment by talllguy** [comment]
Elliott Plack ✅

**Comment by Leandermen** [comment]
Leandro Zamudio ✅

**Comment by engelm1324** [comment]
✅
