### ISSUE TITLE
Callback to app doesn't work

### ISSUE THREAD

**Issue by marikavertzonis** [xiao8579/QuickCapture-Testing#32]
**Describe the bug**
Survey123 callback doesn't go back the QuickCapture app on Windows, it launches the web page

When you go to the project json you can see that the callback is written as an app link (quickcapture.arcgis.app). it should be a custom url (arcgis-quickcapture) see the screenshot below

**To Reproduce**
1. Create a link button to Survey123 with callback enabled
2. Launch project in QuickCapture on Windows
3. Click the new link button. it goes to Survey123, capture feature in Survey123 and click the tick.
4. the QuickCapture web page (to download app) is launched instead of the app

**Screenshots**
![image](https://devtopia.esri.com/storage/user/106/files/b44caf80-f371-11ea-8938-d5a122868c92)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by glenshep** [comment]
Same issue in iOS

Device: iPhone 7
Version: 13.3.1
Survey123: 3.9.149

Updated to Survey123 3.10.323 - Callback was successful

**Comment by glenshep** [comment]
Worked successfully on another device:

Device: iPhone 8
Version: 13.6.1
Survey123: 3.10.323

**Comment by marikavertzonis** [comment]
https://devtopia.esri.com/Melbourne/QuickCapture-Web/issues/1082

**Comment by xiao8579** [comment]
fixed.
