### ISSUE TITLE
[BUG] Missing Data Recovery Email when Saving as or Creating from Template

### ISSUE THREAD

**Issue by IsmaelInRedlands** [xiao8579/QuickCapture-Testing#4]
**Describe the bug**
When using the save as option or creating a project from a template, the Data Recovery Email is empty. 

**To Reproduce**
1. In the designer gallery, click on create project from template
2. Select template
3. The email is empty. Needs to be manually filled out

**Expected behavior**
The Data Recovery Email should be auto-completed using the currently logged-in user email, which can be found in the ArcGIS account profile.

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/5918689/77676573-bea5f900-6f4b-11ea-958e-a02464a93a43.png)

**Website (please complete the following information):**

**Mobile (please complete the following information):**

**Additional context**

**Comment by xiao8579** [comment]
Bug fixed on1.5 devext. Closing.
