### ISSUE TITLE
Download 1.10.27 build

### ISSUE THREAD

**Issue by xiao8579** [xiao8579/QuickCapture-Testing#41]
Android and Windows

- Windows: https://earlyadopter.esri.com/download/606273b13cd840e98832f51d06d4921c/ArcGISQuickCaptureBeta_x64.exe.zip
- Android: https://earlyadopter.esri.com/download/8bbd7c9e03f7414cbb40598d69cd34c2/ArcGISQuickCaptureBeta_1_10_27.apk

iOS

**Comment by jerjer007** [comment]
No problems, download worked smoothly. Using iPhone 12 pro max.  General settings/Device Management/ESRI Enterprise good to go.
