### ISSUE TITLE
Side by side showing in phone

### ISSUE THREAD

**Issue by IsmaelInRedlands** [xiao8579/QuickCapture-Testing#45]
Two users reported today that map and buttons are showing side by side in phone even when the option is disabld in designr
* https://github.com/xiao8579/QuickCapture-Testing/issues/39#issuecomment-811310177
* Jerry
* 
![image](https://user-images.githubusercontent.com/5918689/113199775-5ce23400-921c-11eb-9685-1677ef97979b.png)

**Comment by xiao8579** [comment]
fixed.
