### ISSUE TITLE
Oriented Imagery does not work if using a Point Layer that is not in the first position with a Hosted Feature Layer

### ISSUE THREAD

**Issue by kayleerivera** [xiao8579/QuickCapture-Testing#54]
**Describe the bug**
Oriented Imagery does not work if using a Point Layer that is not in the first position with a Hosted Feature Layer.

**To Reproduce**
1. Create a Hosted Feature Layer with at least two Point layers. I did this using Survey123 with a geopoint question inside a repeat section. (My layers were named "Streetlight Inventory" and "oriented_imagery")
2. Create QuickCapture project from an existing feature layer
3. Remove the "Streetlight Inventory" from the QC project (or whatever layer was in the first position in the Hosted Feature Layer.
4. Enable Oriented Imagery for the "oriented_imagery" layer (or layer in second position in HFL)
5. Save Project.
6. Collect Data.
7. View Oriented Imagery for the project. No points are visible.
8. I added points to the "Streetlight Inventory" (1st layer) manually.
9. View Oriented Imagery for the project. 
10. Oriented Imagery viewer show points from "Streetlight Inventory" but not "oriented_imagery" layers. The viewer also tries to create a coverage map based on "Streetlight Inventory" layer, but I'm not sure where it's pulling this coverage from. Additionally, give "Failed to load image" error.

**Expected behavior**
I expected my oriented_imagery layer to show points/coverage, as opposed to Streetlight Inventory.

**Screenshots**
Overview Pane for Hosted Feature Layer, showing Streetlight Inventory in first position, and oriented_imagery layer in second position.
![image](https://user-images.githubusercontent.com/71770759/136442777-32b7c0f4-8f50-4b4c-9e0e-71ea89d77d3c.png)

Result - Streetlight Inventory points (manually entered from desktop), with coverage that does not apply.
![image](https://user-images.githubusercontent.com/71770759/136442596-1d9b2870-c9b9-48c5-af33-a79779b7315c.png)

**Website (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94.0.4606.71 

**Mobile (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 14.8
 - Version: QC Version 1.11.84

**Comment by xiao8579** [comment]
Issue will be addressed in version 1.12
