### ISSUE TITLE
"New Folder" Option

### ISSUE THREAD

**Issue by ChaseFisher** [xiao8579/QuickCapture-Testing#6]
**Describe the enhancement**
When creating a new project or launching a template. Giving the user an option to create a new folder in their ArcGIS online or portal would be a nice addition. 

**Describe the user impact**
Allows them to maintain the organization of their projects and data because they are not going to know for sure what is all being launched with a template. This would keep them from looking for all the components to make a template work. They will know it is all in one location.

**Comment by xiao8579** [comment]
Enhancement added in 1.6 web designer.
