### ISSUE TITLE
qaext

### ISSUE THREAD

**Issue by dabneyhopkins** [xiao8579/QuickCapture-Testing#7]
I can't find the web address that was shown briefly on the screen so I feel like I'm missing stuff using older projects like Bike Trails.

**Comment by xiao8579** [comment]
Hi @dabneyhopkins not sure your problem here. Do you have trouble connecting to qaext (it's documented in [WIKI](https://github.com/xiao8579/QuickCapture-Testing/wiki))? Or which link are you looking for?

**Comment by xiao8579** [comment]
Resolved.
