### ISSUE TITLE
Dashboard link in Preview of Template not Showing Layer

### ISSUE THREAD

**Issue by ChaseFisher** [xiao8579/QuickCapture-Testing#8]
**Describe the bug**
When looking at Template for Police Officer Reporter if you choose preview and then click on the link for dashboard. Once the App loads you get a notice... "The layer, Police Officer Reporter - Direction, cannot be added to the map. " and the option to click OK to close the dialog box. 

**To Reproduce**
1. Go to 'Create from Template'
2. Click on 'Preview'
3. Click on Dashboard link in description to the left '....'

**Expected behavior**
I initially expected to see an operations dashboard with simulated data. 

**Screenshots**

![image](https://user-images.githubusercontent.com/62716334/77679707-e9e71300-6f60-11ea-9264-69e6a3cf22c2.png)

**Website (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Version 80.0.3987.149 (Official Build) (64-bit)]

**Mobile (please complete the following information):**
NA

**Comment by xiao8579** [comment]
It looks like the layer "Police officer reporter- direction" no longer exists and is not used in the template project neither. I've removed this feature service from the web map (and the dashboard).

**Comment by ChaseFisher** [comment]
The Indicators at the bottom of the map within the app show no data. I assume they were linked to that layer?

**Comment by xiao8579** [comment]
Fixed the web app display.

**Comment by ChaseFisher** [comment]
Looks Awesome! Nice Work.
